server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: EMP-SERVICE
          uri: lb://EMP-SERVICE
          predicates:
            - Path=/employee/**
        - id: SCHOOL-SERVICE
          uri: lb://SCHOOL-SERVICE
          predicates:
            - Path=/school/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
  instance:
    hostname: eureka-0
    prefer-ip-address: true